LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := FMRadioFix
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := FMRadio.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_OVERRIDES_PACKAGES := FMRadio
include $(BUILD_PREBUILT)
